jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      pip install --upgrade pip
      pip install conan --upgrade
      pip install conan_package_tools bincrafters_package_tools
      SET CONAN_VISUAL_VERSIONS="15"
      python build.py
    env:
      CONAN_PASSWORD: $(CONAN_PASSWORD)
  strategy:
    matrix:
      Release:
        CONAN_BUILD_TYPES: Release
      Debug:
        CONAN_BUILD_TYPES: Debug
